<template>
    <div>
        <van-index-bar>
                <van-index-anchor  v-for="(n,index) in list" :key="index">
                    {{n.title}}
                    <van-cell :title="text.name" v-for="(text,index2) in n.contemt" :key="index2" />
                </van-index-anchor>
        </van-index-bar>
    </div>
</template>

<script>
    import { IndexBar, IndexAnchor,Cell} from 'vant';
    export default {
        name: "look_all_brand",
        components:{
            [IndexAnchor.name]:IndexAnchor,
            [IndexBar.name]:IndexBar,
            [Cell.name]:Cell
        },
        data(){
            return{
                list:[
                    {
                        "title":"A",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"B",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"C",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"D",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"E",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"F",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"G",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"H",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"I",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"J",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"K",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"L",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"M",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"N",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"O",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"P",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"Q",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"R",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"S",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"T",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"U",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"V",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"W",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"X",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"Y",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    },
                    {
                        "title":"Z",
                        contemt:[
                            {name:"aas"},
                            {name:"aas"},
                            {name:"aas"}
                        ]
                    }

                ]
            }
        }
    }
</script>

<style scoped>

</style>